[package]
name = "abyness"
version = "0.1.0"
description = "像素级复刻 Typora 的所见即所得 Markdown 编辑器"
authors = ["you"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "abyness_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
